# Generated by Django 5.1.6 on 2025-02-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=30, null=True, unique=True)),
            ],
        ),
    ]
