# Generated by Django 5.1.6 on 2025-03-03 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_userdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("number", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("balance", models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bank account",
                "verbose_name_plural": "Bank accounts",
            },
        ),
        migrations.CreateModel(
            name="BankCard",
            fields=[
                ("number", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("available_balance", models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ("expiration_date", models.DateField()),
                ("cvv", models.CharField(max_length=3)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="app.bankaccount")),
            ],
            options={
                "verbose_name": "Bank card",
                "verbose_name_plural": "Bank cards",
            },
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255, null=True, unique=True)),
                ("phone_number", models.CharField(max_length=30, null=True, unique=True)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Telegram User",
                "verbose_name_plural": "Telegram Users",
            },
        ),
        migrations.DeleteModel(
            name="UserData",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="app.telegramuser"),
        ),
    ]
