# Generated by Django 5.1.7 on 2025-03-28 07:37

import django.contrib.postgres.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_bankaccount_bankcard_telegramuser_delete_userdata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankcard",
            name="available_balance",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="list_of_favourites",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255, unique=True), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="bankcard",
            name="number",
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__length__gte", 20)), name="bankaccount_number_length"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.CheckConstraint(condition=models.Q(("balance__gte", Decimal("0"))), name="price_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="bankcard",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__length__gte", 16)), name="bankcard_number_length"
            ),
        ),
    ]
