# Generated by Django 5.1.7 on 2025-03-22 15:41

import app.internal.models.user_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_bankaccount_bankcard_telegramuser_delete_userdata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="list_of_favourites",
            field=models.JSONField(default=app.internal.models.user_data.TelegramUser.set_favourites),
        ),
    ]
