# Generated by Django 5.1.7 on 2025-03-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_telegramuser_list_of_favourites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankcard",
            name="available_balance",
        ),
    ]
