# Generated by Django 5.1.7 on 2025-03-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_bankcard_available_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankcard",
            name="number",
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__length__gte", 20)), name="bankaccount_number_length"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankcard",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__length__gte", 16)), name="bankcard_number_length"
            ),
        ),
    ]
