# Generated by Django 5.1.7 on 2025-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_telegramuser_date_joined_telegramuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="password",
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
