# Generated by Django 5.1.7 on 2025-03-24 17:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_bankcard_number_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.CheckConstraint(condition=models.Q(("balance__gte", Decimal("0"))), name="price_gte_0"),
        ),
    ]
