# Generated by Django 5.1.7 on 2025-05-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_telegramuser_is_staff_alter_telegramuser_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="is_viewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="photo_name",
            field=models.CharField(blank=True, default=None, null=True, unique=True),
        ),
    ]
