# Generated by Django 5.1.7 on 2025-05-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_transactionhistory_is_viewed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionhistory",
            name="photo_name",
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="photo",
            field=models.ImageField(default=None, null=True, unique=True, upload_to=""),
        ),
    ]
