channels:
  - name: cloud_monitoring
    channel:
      pipe:
        - storage_ref:
            name: main
      output:
        plugin: yc_metrics
        config:
          url: https://monitoring.api.cloud.yandex.net/monitoring/v2/data/write
          folder_id: b1gp32p294a8feuf1g4v
          iam:
            cloud_meta: {}
routes:
  - input:
      plugin: metrics_pull
      config:
        url: http://158.160.167.78:9090/metrics
        format:
          prometheus: {}
        namespace: app
    channel:
      channel_ref:
        name: cloud_monitoring
