stages:
  - build
  - deploy
build-job:
  stage: build
  script:
    - make build push
  tags:
    - job:build
  evironment:
    name: test
deploy-job:
  stage: deploy
  script:
    - make pull down migrate up
  tags:
    - job:deploy.prod/1
  evironment:
    name: prod
before_script:
  - apk add make
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - cp $DOT_ENV $(pwd)/.env
