image: docker:28.0.1
stages:
  - test
  - build
  - deploy
test-job:
  stage: test
  image: python:3.13.2-slim
  before_script:
    - cp $DOT_ENV $(pwd)/.env
  services:
    - name: postgres:17.4
      alias: postgres
  script:
    - pip install --no-cache-dir poetry
    - poetry config virtualenvs.create false
    - poetry install --no-interaction --no-cache --no-root --no-directory --with dev
    - pytest -ra -n auto
  variables:
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_DB: test
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: test
  tags:
    - job:test
  environment:
    name: test
build-job:
  stage: build
  script:
    - make build push
  tags:
    - job:build
  # only:
  #   - main
  environment:
    name: prod
deploy-job:
  stage: deploy
  script:
    - make pull down up
  tags:
    - job:deploy.prod/1
  # only:
  #   - main
  environment:
    name: prod
before_script:
  - apk add make
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - cp $DOT_ENV $(pwd)/.env
