services:
  postgres:
    image: postgres:17.4
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  django-bot:
    image: $IMAGE_APP
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
    env_file:
      - .env
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py run_bot"
  django-web:
    image: $IMAGE_APP
    expose:
      - "8000"
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
    env_file:
      - .env
    volumes:
      - static:/app/static
      - media:/app/media
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn config.wsgi --bind 0.0.0.0:8000"
  nginx:
    image: $IMAGE_NGINX
    ports:
      - 6000:80
    volumes:
      - static:/src/static
      - media:/src/media

volumes:
  postgres:
  static:
  media:
