services:
  postgres:
    image: postgres:17.4
    ports:
      - 5432:5432
    env_file:
      - .env
  localstack:
    image: localstack/localstack:stable
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    env_file:
      - .env
