services:
  postgres:
    image: postgres:17.4
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  django-bot:
    image: registry.gitlab.com/frukun1/doubletapp-django/django:latest
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
    env_file:
      - .env
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py run_bot"
  django-web:
    image: registry.gitlab.com/frukun1/doubletapp-django/django:latest
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
    env_file:
      - .env
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
