services:
  postgres:
    image: postgres:17.4
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - .env
  test-container:
    build:
      dockerfile: ./test.Dockerfile
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    command: bash -c "python src/manage.py migrate && pytest"
