services:
  postgres:
    image: postgres:17.4
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  django-bot:
    image: $IMAGE_APP
    build: .
    expose:
      - $PORT
      - 9090:9090
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
    env_file:
      - .env
    command: bash -c "python manage.py run_bot"
  django-web:
    image: $IMAGE_APP
    build: .
    expose:
      - $PORT
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
    env_file:
      - .env
    volumes:
      - static:/app/static
      - media:/app/media
    command: bash -c "python manage.py migrate app && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn config.wsgi --bind 0.0.0.0:8000"
  nginx:
    image: $IMAGE_NGINX
    build: nginx/.
    ports:
      - 6000:80
    env_file:
      - .env
    volumes:
      - static:/src/static
      - media:/src/media
  ua:
    image: $IMAGE_UA
    build: unified_agent/.
    ports:
      - 16241:16241
    env_file:
      - .env
volumes:
  postgres:
  static:
  media:
